export type ErrorCode =
  | "ACCESS_DENIED"
  | "INVALID_REQUEST"
  | "INVALID_STATE"
  | "INTERNAL_SERVER_ERROR"
  | "ROOM_CAPACITY_INVALID"
  | "ROOM_TITLE_INVALID"
  | "ROOM_NOT_FOUND"
  | "ROOM_FULL"
  | "ROOM_IN_GAME"
  | "HOST_CANNOT_READY"
  | "ROOM_NUMBER_ERROR"
  | "ROOM_PAGING_PARAMETER_INVALID"
  | "ROOM_ID_ALREADY_EXISTS"
  | "PLAYER_ID_ALREADY_EXISTS"
  | "ONLY_HOST_CAN_START_GAME"
  | "NOT_ENOUGH_PLAYERS_TO_START"
  | "PLAYERS_NOT_READY"
  | "USER_ALREADY_IN_ROOM"
  | "ROOM_ALREADY_STARTED"
  | "ROOM_NOT_STARTED"
  | "PLAYER_NOT_IN_ANY_ROOM"
  | "PLAYER_NOT_IN_ROOM"
  | "USER_NOT_FOUND"
  | "GAME_NOT_FOUND"
  | "GAME_NOT_IN_PROGRESS"
  | "GAME_IN_PROGRESS"
  | "GAME_ALREADY_EXISTS"
  | "SUBMIT_CHOICE_NOT_CURRENT_QUIZ"
  | "SUBMIT_CHOICE_IS_AFTER_DEADLINE"
  | "QUIZ_NOT_FOUND"
  | "QUIZ_CHOICE_NUMBER_MAPPING_NOT_FOUND";

export interface ErrorWebSocketMessage {
  type: "ERROR";
  code: ErrorCode;
  message: string;
}
