spring:
  application:
    name: sigkill-server

# Session Configuration
server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        same-site: none
        secure: true
        path: /
      timeout: 24h

logging:
  file:
    name: /var/log/sigkill/app.log