spring:
  application:
    name: sigkill-server

  data:
    redis:
      host: localhost
      port: 6379


# Session Configuration
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: true
        same-site: lax
        # TODO: Set to true in production with HTTPS
        secure: false
        path: /
      timeout: 24h

